### ISSUE TITLE
Test program cannot run correctly

### ISSUE THREAD

**Issue by cwk08** [mstniy/safepm#2]
I'm trying to run the test program in _test_ folder, however, safepm reports bug before the crash point is executed.
Taking **use_after_free.cpp** as a example, what I got from the terminal is as listed below:

```
==63811==ERROR: AddressSanitizer: unknown-crash on address 0x7f24c2c3b0ba at pc 0x7f24ca0d8e33 bp 0x7ffed1804b50 sp 0x7ffed18042f8
WRITE of size 2 at 0x7f24c2c3b0ba thread T0
    #0 0x7f24ca0d8e32 in __interceptor_memset (/usr/lib/x86_64-linux-gnu/libasan.so.6+0x38e32)
    #1 0x7f24c9e6c1e7 in pmdk_asan_mark_mem (/home/cwk/cwk/safepmdk/lib/libpmemobj.so.1+0x191e7)
    #2 0x7f24c9e87b28 in alloc_additional_work (/home/cwk/cwk/safepmdk/lib/libpmemobj.so.1+0x34b28)
    #3 0x7f24c9e887d8 in pmemobj_tx_xalloc (/home/cwk/cwk/safepmdk/lib/libpmemobj.so.1+0x357d8)
    #4 0x7f24c9e88961 in pmemobj_root (/home/cwk/cwk/safepmdk/lib/libpmemobj.so.1+0x35961)
    #5 0x55d8daceaa59 in main /home/cwk/cwk/safepm/tests/use_after_free.cpp:26
    #6 0x7f24c8d0db96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #7 0x55d8daceb6f9 in _start (/home/cwk/cwk/safepm/tests/output+0x26f9)
Address 0x7f24c2c3b0ba is a wild pointer.
SUMMARY: AddressSanitizer: unknown-crash (/usr/lib/x86_64-linux-gnu/libasan.so.6+0x38e32) in __interceptor_memset
Shadow bytes around the buggy address:
```

use_after_free.cpp:26 refers to this line: ` PMEMoid proot_ = pmemobj_root(pool, sizeof(struct root));`, which should not crash in a normal executing.

**Comment by mstniy** [comment]
Thanks for reporting this issue. Unfortunately I don't currently have the
time to debug it, but would gladly review a merge request.
